---
dependencies:
  - name: activiti-cloud-query
    repository: https://activiti.github.io/activiti-cloud-helm-charts
    version: 7.1.0-M10
    condition: application.activiti-cloud-query.enabled,activiti-cloud-query.enabled
  - name: postgresql
    version: 8.9.6
    repository: https://charts.bitnami.com/bitnami
    condition: application.postgres.enabled,postgres.enabled
    alias: postgres
  - name: rabbitmq
    version: 7.6.8
    repository: https://charts.bitnami.com/bitnami
    condition: application.rabbitmq.enabled,rabbitmq.enabled
  - name: runtime-bundle
    repository: https://activiti.github.io/activiti-cloud-helm-charts
    version: 7.1.0-M10
    condition: application.runtime-bundle.enabled,runtime-bundle.enabled
  - name: activiti-cloud-connector
    repository: https://activiti.github.io/activiti-cloud-helm-charts
    version: 7.1.0-M10
    condition: application.activiti-cloud-connector.enabled,activiti-cloud-connector.enabled
  - name: alfresco-adf-app
    alias: alfresco-process-workspace-app
    version: 7.1.0-M11
    repository: https://kubernetes-charts.alfresco.com/incubator
    condition: application.alfresco-process-workspace-app.enabled,alfresco-process-workspace-app.enabled
  - name: alfresco-adf-app
    alias: alfresco-admin-app
    version: 7.1.0-M11
    repository: https://kubernetes-charts.alfresco.com/incubator
    condition: application.alfresco-admin-app.enabled,alfresco-admin-app.enabled
  - name: alfresco-adf-app
    alias: alfresco-digital-workspace-app
    version: 7.1.0-M11
    repository: https://kubernetes-charts.alfresco.com/incubator
    condition: application.alfresco-digital-workspace-app.enabled,alfresco-digital-workspace-app.enabled
