---
dependencies:
- name: "activiti-cloud-query"
  repository: "https://activiti.github.io/activiti-cloud-helm-charts"
  version: "7.1.332"
  condition: "application.activiti-cloud-query.enabled,activiti-cloud-query.enabled"
- name: "activiti-cloud-audit"
  repository: "https://activiti.github.io/activiti-cloud-helm-charts"
  version: "7.1.325"
  condition: "application.activiti-cloud-audit.enabled,activiti-cloud-audit.enabled"
- name: "rabbitmq-ha"
  repository: "https://kubernetes-charts.storage.googleapis.com"
  version: "1.38.1"
  condition: "application.rabbitmq.enabled,rabbitmq.enabled"
  alias: "rabbitmq"
- name: "postgresql"
  repository: "https://kubernetes-charts.storage.googleapis.com"
  version: "3.11.3"
  condition: "application.postgres.enabled,postgres.enabled"
  alias: "postgres"
- name: "runtime-bundle"
  repository: "https://activiti.github.io/activiti-cloud-helm-charts"
  version: "7.1.397"
  condition: "application.runtime-bundle.enabled,runtime-bundle.enabled"
- name: "activiti-cloud-connector"
  repository: "https://activiti.github.io/activiti-cloud-helm-charts"
  version: "7.1.339"
  condition: "application.activiti-cloud-connector.enabled,activiti-cloud-connector.enabled"
- name: "activiti-cloud-notifications-graphql"
  repository: "https://activiti.github.io/activiti-cloud-helm-charts"
  version: "7.1.358"
  condition: "application.activiti-cloud-notifications-graphql.enabled,activiti-cloud-notifications-graphql.enabled"
- name: "alfresco-process-springboot-service"
  repository: "https://kubernetes-charts.alfresco.com/stable"
  version: "2.1.0"
  condition: "application.alfresco-form-service.enabled,alfresco-form-service.enabled"
  alias: "alfresco-form-service"
- name: "alfresco-process-springboot-service"
  repository: "https://kubernetes-charts.alfresco.com/stable"
  version: "2.1.0"
  condition: "application.alfresco-dmn-runtime-service.enabled,alfresco-dmn-runtime-service.enabled"
  alias: "alfresco-dmn-runtime-service"
- name: "alfresco-process-springboot-service"
  repository: "https://kubernetes-charts.alfresco.com/stable"
  version: "2.1.0"
  condition: "application.alfresco-script-runtime-service.enabled,alfresco-script-runtime-service.enabled"
  alias: "alfresco-script-runtime-service"
- name: "alfresco-process-springboot-service"
  repository: "https://kubernetes-charts.alfresco.com/stable"
  version: "2.1.0"
  condition: "application.alfresco-preference-service.enabled,alfresco-preference-service.enabled"
  alias: "alfresco-preference-service"
- name: "alfresco-adf-app"
  repository: "https://kubernetes-charts.alfresco.com/stable"
  version: "2.1.3"
  condition: "application.alfresco-process-workspace-app.enabled,alfresco-process-workspace-app.enabled"
  alias: "alfresco-process-workspace-app"
- name: "alfresco-adf-app"
  repository: "https://kubernetes-charts.alfresco.com/stable"
  version: "2.1.3"
  condition: "application.alfresco-admin-app.enabled,alfresco-admin-app.enabled"
  alias: "alfresco-admin-app"
