dependencies:
  - name: application
    alias: activiti-cloud-application
    version: 1.1.8
    repository: https://activiti.github.io/activiti-cloud-charts
  - name: activiti-cloud-modeling
    version: 1.1.7
    repository: https://activiti.github.io/activiti-cloud-charts
    condition: activiti-cloud-modeling.enabled
  - name: alfresco-adf-app
    alias: alfresco-admin-app
    version: 2.1.3
    repository: https://kubernetes-charts.alfresco.com/incubator
    condition: alfresco-admin-app.enabled
  - name: alfresco-adf-app
    alias: alfresco-process-workspace-app
    version: 2.1.3
    repository: https://kubernetes-charts.alfresco.com/incubator
    condition: alfresco-process-workspace-app.enabled
