dependencies:
  - name: common
    repository: https://activiti.github.io/activiti-cloud-helm-charts
    version: 7.1.0-M12
    alias: activiti-cloud-query
    condition: application.activiti-cloud-query.enabled,activiti-cloud-query.enabled
  - name: postgresql
    version: 9.1.1
    repository: https://charts.bitnami.com/bitnami
    condition: application.postgresql.enabled,postgresql.enabled
  - name: rabbitmq
    version: 7.8.0
    repository: https://charts.bitnami.com/bitnami
    condition: application.rabbitmq.enabled,rabbitmq.enabled
  - name: common
    repository: https://activiti.github.io/activiti-cloud-helm-charts
    version: 7.1.0-M12
    alias: runtime-bundle
    condition: application.runtime-bundle.enabled,runtime-bundle.enabled
  - name: common
    repository: https://activiti.github.io/activiti-cloud-helm-charts
    version: 7.1.0-M12
    alias: activiti-cloud-connector
    condition: application.activiti-cloud-connector.enabled,activiti-cloud-connector.enabled
  - name: common
    repository: https://activiti.github.io/activiti-cloud-helm-charts
    version: 7.1.0-M12
    alias: alfresco-process-workspace-app
    condition: application.alfresco-process-workspace-app.enabled,alfresco-process-workspace-app.enabled
  - name: common
    repository: https://activiti.github.io/activiti-cloud-helm-charts
    version: 7.1.0-M12
    alias: alfresco-admin-app
    condition: application.alfresco-admin-app.enabled,alfresco-admin-app.enabled
  - name: common
    repository: https://activiti.github.io/activiti-cloud-helm-charts
    version: 7.1.0-M12
    alias: alfresco-digital-workspace-app
    condition: application.alfresco-digital-workspace-app.enabled,alfresco-digital-workspace-app.enabled
