# Default values for alfresco-process-application.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
# README documentation generated automatically from this file via https://github.com/norwoodj/helm-docs

# global -- for common values see https://github.com/Activiti/activiti-cloud-common-chart/blob/master/charts/common/README.md
global:
  # global.registryPullSecrets -- Configure pull secrets for all deployments
  registryPullSecrets:
    - quay-registry-secret
  applicationVersion: "1"
  keycloak:
    # global.keycloak.host -- Configure Keycloak host template, i.e. "{{ .Release.Namespace }}.{{ .Values.global.gateway.domain }}"
    host: '{{ template "common.gateway-host" . }}'
    # global.keycloak.url -- Set full url to configure external Keycloak, https://keycloak.mydomain.com/auth
    url: ""
    # global.keycloak.realm -- Configure Keycloak realm
    realm: activiti
    # global.keycloak.resource -- Configure Keycloak resource
    resource: "{{ .Release.Name }}"
  gateway:
    # global.gateway.host -- Set to configure single host domain name for all services, i.e. "{{ .Release.Namespace }}.{{ template "common.gateway-domain" . }}"
    host: '{{ template "common.gateway-domain" . }}'
    # global.gateway.http -- Set to false enables HTTPS configuration on all urls
    http: false
    # global.gateway.tlsacme -- Set to enable automatic TLS for ingress if https is enabled
    tlsacme: false
    # global.gateway.domain -- Set to configure gateway domain template, i.e. {{ .Release.Namespace }}.1.3.4.5.nip.io
    # $ helm upgrade aae . --install --set global.gateway.domain=1.2.3.4.nip.io
    domain: ""
    # global.gateway.annotations -- Configure global annotations for all service ingresses
    annotations: {}
  acs:
    # global.acs.enabled -- enable support for ACS
    enabled: false
  rabbitmq:
    host: ""
    username: guest
    password: guest
activiti-cloud-query:
  enabled: true
  nameOverride: activiti-cloud-query
  service:
    name: query
  javaOpts:
    xmx: 2048m
    xms: 512m
  activiti:
    keycloak:
      clientPassword: client
  postgresql:
    enabled: false
  db:
    # activiti-cloud-query.db.ddlAuto -- set to 'none' temporarily rather than default 'validate' that breaks
    ddlAuto: none
  rabbitmq:
    enabled: true
  image:
    repository: quay.io/alfresco/alfresco-process-query-service
    tag: 7.1.0-M12
    pullPolicy: Always
  liquibase:
    enabled: true
  ingress:
    path: /{{ .Release.Name }}
    subPaths:
      - /query/?(.*)
      - /audit/?(.*)
      - /notifications/?(.*)
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
      nginx.ingress.kubernetes.io/enable-cors: "true"
      nginx.ingress.kubernetes.io/cors-allow-headers: "*"
      nginx.ingress.kubernetes.io/rewrite-target: /$1
  probePath: /actuator/health
  resources:
    limits:
      cpu: "1.5"
      memory: 2048Mi
    requests:
      cpu: 200m
      memory: 512Mi
  extraEnv: |
    - name: SERVER_PORT
      value: "8080"
    - name: SERVER_USEFORWARDHEADERS
      value: "true"
    - name: SERVER_TOMCAT_INTERNALPROXIES
      value: ".*"
    - name: KEYCLOAK_USERESOURCEROLEMAPPINGS
      value: "false"
    - name: ACTIVITI_KEYCLOAK_CLIENT_PASSWORD
      value: '{{ .Values.activiti.keycloak.clientPassword }}'
    - name: ACTIVITI_CLOUD_APPLICATION_NAME
      value: "{{ .Release.Name }}"
    - name: GRAPHIQL_GRAPHQL_WS_PATH
      value: '/{{ .Release.Name }}/notifications/ws/graphql'
    - name: GRAPHIQL_GRAPHQL_WEB_PATH
      value: '/{{ .Release.Name }}/notifications/graphql'
    - name: SPRING_SLEUTH_INTEGRATION_PATTERNS
      value: '!hystrixStreamOutput*,!channel*,!clientInboundChannel*,!clientOutboundChannel*,!brokerChannel*,*'
      
  extraVolumes: |
    - name: keystore-volume
      emptyDir: {}
    - name: rootca
      secret:
        secretName: rootca
    - name: license
      secret:
        secretName: licenseaps
  extraVolumeMounts: |
    - name: license
      mountPath: "/root/.activiti/enterprise-license/"
      readOnly: true
    - name: keystore-volume
      mountPath:  /usr/java/openjdk-11.0.10_9/lib/security/
  affinity: {}
  extraInitContainers: |-
    - name: java-certificate
      image: quay.io/alfresco/alfresco-process-query-service:7.1.0-M12
      command: ["/bin/sh"]
      args:
      - -c
      - |
        keytool -import -alias alfresco-azure -cacerts -file /tmp/rootca/root_ca.pem -storepass changeit -noprompt
        cp -R  /usr/java/openjdk-11.0.10_9/lib/security/* /tmp/security/

      volumeMounts:
      - name: keystore-volume
        mountPath: /tmp/security
      - name: rootca
        mountPath: /tmp/rootca
runtime-bundle:
  enabled: true
  nameOverride: runtime-bundle
  service:
    name: rb
  javaOpts:
    xmx: 2048m
    xms: 512m
  image:
    repository: activiti/example-runtime-bundle
    tag: 7.1.1037
    pullPolicy: Always
  ingress:
    path: /{{ .Release.Name }}/rb
    annotations:
      kubernetes.io/ingress.class: nginx
      nginx.ingress.kubernetes.io/enable-cors: "true"
      nginx.ingress.kubernetes.io/cors-allow-headers: Authorization, Content-Type, Accept
  postgresql:
    enabled: false
  rabbitmq:
    enabled: true
  resources:
    limits:
      cpu: "2"
      memory: 2048Mi
    requests:
      cpu: 200m
      memory: 512Mi
  probePath: '{{ tpl .Values.ingress.path . }}/actuator/health'
  extraEnv: |-
    - name: SPRING_APPLICATION_NAME
      value: "rb"
    - name: SERVER_SERVLET_CONTEXTPATH
      value: "{{ tpl .Values.ingress.path . }}"
    - name: SERVER_USEFORWARDHEADERS
      value: "true"
    - name: SERVER_TOMCAT_INTERNALPROXIES
      value: ".*"
  extraInitContainers: |-
    - name: java-certificate
      image: activiti/example-runtime-bundle:7.1.1037
      command: ["/bin/sh"]
      args:
      - -c
      - |
        keytool -import -alias alfresco-azure -cacerts -file /tmp/rootca/root_ca.pem -storepass changeit -noprompt
        cp -R  /opt/java/openjdk/lib/security/* /tmp/security/

      volumeMounts:
      - name: keystore-volume
        mountPath: /tmp/security
      - name: rootca
        mountPath: /tmp/rootca
  extraVolumes: |
    - name: keystore-volume
      emptyDir: {}
    - name: rootca
      secret:
        secretName: rootca

  extraVolumeMounts: |
    - name: keystore-volume
      mountPath:  /opt/java/openjdk/lib/security/
activiti-cloud-connector:
  enabled: true
  nameOverride: example-cloud-connector
  image:
    repository: activiti/example-cloud-connector
    tag: 7.1.1038
    pullPolicy: Always
  rabbitmq:
    enabled: true
  postgresql:
    enabled: false  
  ingress:
    enabled: true
    path: "/{{ .Release.Name }}/{{ .Values.nameOverride }}"
    annotations:
      kubernetes.io/ingress.class: nginx
      nginx.ingress.kubernetes.io/enable-cors: "true"
      nginx.ingress.kubernetes.io/cors-allow-headers: "*"
  probePath: "{{ tpl .Values.ingress.path . }}/actuator/health"
  extraEnv: |
    - name: SERVER_PORT
      value: "8080"
    - name: SERVER_SERVLET_CONTEXTPATH
      value: "{{ tpl .Values.ingress.path . }}"
    - name: SERVER_USEFORWARDHEADERS
      value: "true"
    - name: SERVER_TOMCAT_INTERNALPROXIES
      value: ".*"
    - name: ACTIVITI_CLOUD_APPLICATION_NAME
      value: "{{ .Release.Name }}"
  affinity: {}
alfresco-process-workspace-app:
  enabled: false
  nameOverride: process-workspace-app
  service:
    name: apw-app
    envType: frontend
  image:
    repository: quay.io/alfresco/alfresco-process-workspace-app
    tag: develop
    pullPolicy: Always
  ingress:
    path: "/{{ .Release.Name }}/workspace"
  env:
    APP_CONFIG_AUTH_TYPE: "OAUTH"
    APP_CONFIG_BPM_HOST: '{{ include "common.gateway-url" . }}'
    APP_CONFIG_APPS_DEPLOYED: '[{"name": "{{ .Release.Name }}" }]'
alfresco-digital-workspace-app:
  enabled: false
  nameOverride: digital-workspace-app
  ingress:
    path: "/{{ .Release.Name }}/digital-workspace"
  image:
    repository: quay.io/alfresco/alfresco-digital-workspace
    tag: develop
    pullPolicy: Always
  service:
    name: adw-app
    envType: frontend
  env:
    APP_CONFIG_AUTH_TYPE: "OAUTH"
    APP_CONFIG_BPM_HOST: '{{ include "common.gateway-url" . }}'
    APP_CONFIG_ECM_HOST: '{{ include "common.gateway-url" . }}'
    APP_CONFIG_APPS_DEPLOYED: '[{"name": "{{ .Release.Name }}" }]'
    APP_CONFIG_PROVIDER: "ALL"
    APP_CONFIG_IDENTITY_HOST: '{{ include "common.keycloak-url" . }}/admin/realms/{{ include "common.keycloak-realm" . }}'
alfresco-admin-app:
  enabled: false
  nameOverride: admin-app
  service:
    name: admin-app
    envType: frontend
  ingress:
    path: "/{{ .Release.Name }}/admin"
  image:
    repository: quay.io/alfresco/alfresco-admin-app
    tag: develop
    pullPolicy: Always
  env:
    APP_CONFIG_AUTH_TYPE: OAUTH
    APP_CONFIG_BPM_HOST: '{{ include "common.gateway-url" . }}'
    APP_CONFIG_IDENTITY_HOST: '{{ include "common.keycloak-url" . }}/admin/realms/{{ include "common.keycloak-realm" . }}'
    APP_CONFIG_APPS_DEPLOYED: '[{"name": "{{ .Release.Name }}" }]'
postgresql:
  enabled: true
  image:
    repository: postgres
    tag: 11.7
  postgresqlPassword: password
  postgresqlDataDir: /var/lib/postgresql/data/pgdata
  resources:
    requests:
      cpu: 350m
      memory: 512Mi
  commonAnnotations:
    application: activiti
rabbitmq:
  enabled: true
  extraPlugins: ""
  livenessProbe:
    timeoutSeconds: 90
  readinessProbe:
    timeoutSeconds: 90
  persistence:
    storageClass:
    accessMode: ReadWriteOnce
  auth:
    username: guest
    password: guest
    erlangCookie: ylY79lOdNUWsJEwAGdVQnhjSazV4QZKO=
  resources:
    requests:
      cpu: 350m
      memory: 512Mi
    limits:
      cpu: "1"
      memory: 2Gi
  replicaCount: 1
  ingress:
    enabled: false
    hostName: "REPLACEME"
    path: /rabbitmq
volumeinit:
  enabled: false
  # volumeinit.image -- REPLACE with your image containing project files
  image:
    repository: alfresco/example-application-project
    tag: latest
    pullPolicy: Always
persistence:
  enabled: true
  storageClassName:
  accessModes:
    - ReadWriteOnce
  baseSize: 1Gi
kafka:
  enabled: false
  zookeeper:
    enabled: false
  replicaCount: 3
  externalZookeeper:
    servers: activiti-zookeeper
zookeeper:
  enabled: false
  replicaCount: 3
  auth:
    enabled: false
  allowAnonymousLogin: true
activiti-cloud-identity:
  enabled: true
  nameOverride: keycloak
  rbac:
    create: false
  serviceAccount:
    create: false
  postgresql:
    persistence:
      enabled: true
    commonAnnotations:
      application: keycloak
    nameOverride: postgresql-id
    postgresqlPassword: "keycloak"
    resources:
      requests:
        cpu: 300m
        memory: 250Mi
      limits:
        cpu: "1"
        memory: 500Mi
  # image:
  #   repository: alfresco/alfresco-identity-service
  #   tag: 1.4.0-SNAPSHOT
  #   pullPolicy: IfNotPresent
  ingress:
    enabled: true
    rules:
      - host: '{{ include "common.keycloak-host" . }}'
        paths:
          - /auth
    tls: []
    annotations:
      kubernetes.io/ingress.class: nginx
      nginx.ingress.kubernetes.io/proxy-buffer-size: 128k
      nginx.ingress.kubernetes.io/affinity: cookie
      nginx.ingress.kubernetes.io/session-cookie-name: identity_affinity_route
      nginx.ingress.kubernetes.io/session-cookie-hash: sha1
      nginx.ingress.kubernetes.io/enable-cors: "false" # disable NGINX CORS as it's managed by Identity Service
  username: admin
  password: admin
  persistence:
    deployPostgres: true
    dbVendor: postgres
    dbPassword: keycloak
  extraVolumes: |
    - name: realm-secret
      secret:
        secretName: realm-secret
  extraVolumeMounts: |
    - name: realm-secret
      mountPath: "/realm/"
      readOnly: true
  extraEnv: |-
    - name: KEYCLOAK_USER
      value: {{ .Values.username }}
    - name: KEYCLOAK_PASSWORD
      value: {{ .Values.password }}
    - name: PROXY_ADDRESS_FORWARDING
      value: "true"
    - name: KEYCLOAK_IMPORT
      value: /realm/realm.json
  resources:
    requests:
      memory: "750Mi"
    limits:
      memory: "1024Mi"
  realm:
    extraClients:
    extraGroups:
      - name: hr
        realmRoles:
          - ACTIVITI_USER
      - name: sales
        realmRoles:
          - ACTIVITI_USER
      - name: testgroup
      - name: processadmin
        realmRoles:
          - ACTIVITI_ADMIN
    extraRealmRoles:
    extraClientRoles:
    extraUsers:
      - username: client
        enabled: true
        firstName: client
        lastName: client
        email: client@example.com
        credentials:
          - type: password
            value: client
        realmRoles:
          - ACTIVITI_USER
          - offline_access
          - uma_authorization
        clientRoles:
          realm-management:
            - manage-users
            - manage-clients
            - manage-authorization
            - manage-events
            - manage-realm
            - create-client
            - impersonation
            - realm-admin
          broker:
            - read-token
          account:
            - manage-account
            - view-profile
      - username: admin
        enabled: true
        firstName: admin
        lastName: admin
        email: admin@example.com
        credentials:
          - type: password
            value: password
        realmRoles:
          - offline_access
          - uma_authorization
        clientRoles:
          realm-management:
            - manage-users
            - manage-clients
            - manage-authorization
            - manage-events
            - manage-realm
            - create-client
            - impersonation
            - realm-admin
          broker:
            - read-token
          account:
            - manage-account
            - view-profile
      - username: superadminuser
        enabled: true
        firstName: "Super Admin"
        lastName: "User"
        email: superadminuser@example.com
        credentials:
          - type: password
            value: password
        realmRoles:
          - ACTIVITI_USER
          - ACTIVITI_ADMIN
          - ACTIVITI_MODELER
          - offline_access
          - uma_authorization
        clientRoles:
          realm-management:
            - manage-users
            - manage-clients
            - manage-authorization
            - manage-events
            - manage-realm
            - create-client
            - impersonation
            - realm-admin
          broker:
            - read-token
          account:
            - manage-account
            - view-profile
      - username: hruser
        enabled: true
        firstName: HR
        lastName: User
        email: hruser@example.com
        credentials:
          - type: password
            value: password
        realmRoles:
          - offline_access
          - uma_authorization
          - ACTIVITI_USER
        clientRoles:
          account:
            - manage-account
            - view-profile
        groups:
          - /hr
      - username: processadminuser
        enabled: true
        firstName: "Process Admin"
        lastName: User
        email: processadminuser@example.com
        credentials:
          - type: password
            value: password
        realmRoles:
          - offline_access
          - uma_authorization
          - ACTIVITI_ADMIN
        clientRoles:
          account:
            - manage-account
            - view-profile
        groups:
          - /processadmin
      - username: salesuser
        enabled: true
        firstName: Sales
        lastName: User
        email: salesuser@example.com
        credentials:
          - type: password
            value: password
        realmRoles:
          - offline_access
          - uma_authorization
          - ACTIVITI_USER
        clientRoles:
          account:
            - manage-account
            - view-profile
        groups:
          - /sales
      - username: testuser
        enabled: true
        firstName: Test
        lastName: User
        email: testuser@example.com
        credentials:
          - type: password
            value: password
        realmRoles:
          - offline_access
          - uma_authorization
          - ACTIVITI_USER
        clientRoles:
          account:
            - manage-account
            - view-profile
        groups:
          - /testgroup
      - username: hradmin
        enabled: true
        firstName: HR
        lastName: Admin
        email: hradmin@example.com
        credentials:
          - type: password
            value: password
        realmRoles:
          - offline_access
          - uma_authorization
          - ACTIVITI_USER
          - ACTIVITI_ADMIN
        clientRoles:
          account:
            - manage-account
            - view-profile
        groups:
          - /hr
      - username: testadmin
        enabled: true
        firstName: Test
        lastName: Admin
        email: testadmin@example.com
        credentials:
          - type: password
            value: password
        realmRoles:
          - offline_access
          - uma_authorization
          - ACTIVITI_USER
          - ACTIVITI_ADMIN
        clientRoles:
          account:
            - manage-account
            - view-profile
        groups:
          - /testgroup
      - username: modeler
        enabled: true
        firstName: Modeler
        lastName: User
        email: modeler@example.com
        credentials:
          - type: password
            value: password
        realmRoles:
          - offline_access
          - uma_authorization
          - ACTIVITI_MODELER
        clientRoles:
          account:
            - manage-account
            - view-profile
      - username: modeler-qa
        enabled: true
        firstName: Modeler
        lastName: User
        email: modeler-qa@example.com
        credentials:
          - type: password
            value: password
        realmRoles:
          - offline_access
          - uma_authorization
          - ACTIVITI_MODELER
        clientRoles:
          account:
            - manage-account
            - view-profile
