# Default values for alfresco-process-application.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

alfresco-content-services:
  enabled: false
alfresco-process-infrastructure:
  enabled: false
activiti-cloud-connector:
  enabled: true
runtime-bundle:
  enabled: true

activiti-cloud-application:
  activiti-cloud-notifications-graphql:
    enabled: true
    ingress:
      enabled: true
  activiti-cloud-query:
    image:
      repository: quay.io/alfresco/alfresco-process-query-service
      tag: develop
    ingress:
      enabled: true
  activiti-cloud-audit:
    image:
      repository: quay.io/alfresco/alfresco-process-audit-service
      tag: develop
    ingress:
      enabled: true
  runtime-bundle:
    image:
      repository: quay.io/alfresco/alfresco-process-runtime-bundle-service
      tag: develop
    extraVolumes: |
      - name: license
        secret:
          secretName: licenseaps
    extraVolumeMounts: |
      - name: license
        mountPath: "/root/.activiti/enterprise-license/"
        readOnly: true
    ingress:
      enabled: true
  activiti-cloud-connector:
    image:
      repository: activiti/example-cloud-connector
      tag: 7.0.0.GA
    extraVolumes: |
      - name: license
        secret:
          secretName: licenseaps
    extraVolumeMounts: |
      - name: license
        mountPath: "/root/.activiti/enterprise-license/"
        readOnly: true
    ingress:
      enabled: true
