# Default values for alfresco-process-application.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
# README documentation generated automatically from this file via https://github.com/norwoodj/helm-docs

global:
  # global.registryPullSecrets -- Configure pull secrets for all deployments
  registryPullSecrets:
    - "quay-registry-secret"

  image:
    pullPolicy: "Always"

  keycloak:
    # global.keycloak.host -- Keycloak host template, i.e. "identity.{{ .Release.Namespace }}.{{ .Values.global.gateway.domain }}"
    host: 'identity.{{ include "common.gateway-domain" . }}'

    # global.keycloak.url -- full url to configure external Keycloak, https://keycloak.mydomain.com/auth
    url: ""

    # global.keycloak.realm -- Keycloak realm
    realm: "alfresco"
    resource: "activiti"

  gateway:
    # global.gateway.host -- single domain name for all services, i.e. "gateway.{{ .Release.Namespace }}.{{ .Values.global.gateway.domain }}"
    host: 'gateway.{{ include "common.gateway-domain" . }}'

    # global.gateway.host -- when false enables HTTPS configuration on all urls
    http: "true"

    # global.gateway.host -- enable automatic TLS for ingress if https is enabled
    tlsacme: "true"

    # global.gateway.domain -- gateway domain template, i.e. {{ .Release.Namespace }}.1.3.4.5.nip.io
    # helm upgrade activiti . --install --set global.gateway.domain=1.2.3.4.nip.io
    domain: "REPLACEME"

    # global.gateway.host -- global annotations for all service ingress resources
    annotations:
#      certmanager.k8s.io/issuer: letsencrypt-prod
      nginx.ingress.kubernetes.io/rewrite-target: /$1
      kubernetes.io/ingress.class: nginx
      nginx.ingress.kubernetes.io/enable-cors: "true"
      nginx.ingress.kubernetes.io/cors-allow-headers: "*"

    ## Or simply enable templated domain host coniguration in Jx environment
    # host: "activiti-cloud-gateway.{{ .Release.Namespace }}.{{ .Values.global.gateway.domain }}"
    # domain: *domain ## Sync with Jx expose controller domain conig
    # http: *http ## Sync with Jx expose controller http conig
    # tlsacme: *tlsacme ## Sync with Jx expose controller tlsacme conig

  # global.extraEnv -- YAML formatted string to add extra environment properties to all deployments
  extraEnv: |
#    - name: PROPERTY
#      value: "value"

activiti-cloud-query:
  enabled: true
  nameOverride: query
  postgres:
    enabled: true
  image:
    repository: quay.io/alfresco/alfresco-process-query-service
    tag: develop
  ingress:
    path: /{{ .Release.Name }}
    enabled: true
  probePath: "/actuator/health"
  extraEnv: |
    - name: SERVER_PORT
      value: "8080"
    - name: SERVER_USEFORWARDHEADERS
      value: "true"
    - name: SERVER_TOMCAT_INTERNALPROXIES
      value: ".*"
    - name: MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE
      value: "*"
    - name: KEYCLOAK_USERESOURCEROLEMAPPINGS
      value: "false"
    - name: "ACTIVITI_CLOUD_APPLICATION_NAME"
      value: "{{ .Release.Name }}"
  extraVolumes: |
    - name: license
      secret:
        secretName: licenseaps
  extraVolumeMounts: |
    - name: license
      mountPath: "/root/.activiti/enterprise-license/"
      readOnly: true

runtime-bundle:
  enabled: true
  postgres:
    enabled: true
  image:
    repository: quay.io/alfresco/alfresco-process-runtime-bundle-service
    tag: develop
  ingress:
    enabled: true
    path: /{{ .Release.Name }}
    subPaths:
      - /rb/?(.*)
      - /preference/?(.*)
      - /dmn-runtime/?(.*)
  probePath: /actuator/health
  extraEnv: |
    - name: SERVER_PORT
      value: "8080"
    - name: SERVER_USEFORWARDHEADERS
      value: "true"
    - name: SERVER_TOMCAT_INTERNALPROXIES
      value: ".*"
    - name: MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE
      value: "*"
    - name: "ACTIVITI_CLOUD_APPLICATION_NAME"
      value: "{{ .Release.Name }}"
    - name: ACT_KEYCLOAK_RESOURCE
      value: "{{ .Release.Name }}"
    - name: KEYCLOAK_USERESOURCEROLEMAPPINGS
      value: "true"
    - name: ACT_RB_SERVICE_URL
      value: '{{ include "common.gateway-url" . }}/{{ .Release.Name }}/rb'
  extraVolumes: |
    - name: license
      secret:
        secretName: licenseaps
  extraVolumeMounts: |
    - name: license
      mountPath: "/root/.activiti/enterprise-license/"
      readOnly: true

activiti-cloud-connector:
  enabled: false
  nameOverride: example-cloud-connector
  image:
    repository: activiti/example-cloud-connector
    tag: 7.1.0.M7.MOCK1
  ingress:
    enabled: true
    path: "/{{ .Release.Name }}/{{ .Values.nameOverride }}"
  probePath: "{{ tpl .Values.ingress.path . }}/actuator/health"
  extraEnv: |
    - name: SERVER_PORT
      value: "8080"
    - name: SERVER_SERVLET_CONTEXTPATH
      value: "{{ tpl .Values.ingress.path . }}"
    - name: SERVER_USEFORWARDHEADERS
      value: "true"
    - name: SERVER_TOMCAT_INTERNALPROXIES
      value: ".*"
    - name: MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE
      value: "*"
    - name: "ACTIVITI_CLOUD_APPLICATION_NAME"
      value: "{{ .Release.Name }}"

alfresco-script-runtime-service:
  enabled: true
  nameOverride: script-runtime
  rbac:
    create: false
  serviceAccount:
    create: false
  ingress:
    enabled: true
    path: "/{{ .Release.Name }}/{{ .Values.nameOverride }}"
  extraVolumes: |
    - name: license
      secret:
        secretName: licenseaps
  extraVolumeMounts: |
    - name: license
      mountPath: "/root/.activiti/enterprise-license/"
      readOnly: true
  image:
    repository: quay.io/alfresco/alfresco-script-app-runtime
    tag: develop
    pullPolicy: Always
  postgres:
    enabled: true
  probePath: "/{{ .Release.Name }}/{{ .Values.nameOverride }}/actuator/health"
  extraEnv: |
    - name: SERVER_PORT
      value: "8080"
    - name: SERVER_SERVLET_CONTEXTPATH
      value: "{{ tpl .Values.ingress.path . }}"
    - name: SERVER_USEFORWARDHEADERS
      value: "true"
    - name: SERVER_TOMCAT_INTERNALPROXIES
      value: ".*"
    - name: MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE
      value: "*"
    - name: "ACTIVITI_CLOUD_APPLICATION_NAME"
      value: "{{ .Release.Name }}"

alfresco-form-service:
  enabled: true
  nameOverride: form
  rbac:
    create: false
  serviceAccount:
    create: false
  ingress:
    enabled: true
    path: "/{{ .Release.Name }}/{{ .Values.nameOverride }}"
  extraVolumes: |
    - name: license
      secret:
        secretName: licenseaps
  extraVolumeMounts: |
    - name: license
      mountPath: "/root/.activiti/enterprise-license/"
      readOnly: true
  image:
    repository: quay.io/alfresco/alfresco-form-service
    tag: develop
    pullPolicy: Always
  postgres:
    enabled: true
  probePath: "/{{ .Release.Name }}/{{ .Values.nameOverride }}/actuator/health"
  extraEnv: |
    - name: SERVER_PORT
      value: "8080"
    - name: SERVER_SERVLET_CONTEXTPATH
      value: "{{ tpl .Values.ingress.path . }}"
    - name: SERVER_USEFORWARDHEADERS
      value: "true"
    - name: SERVER_TOMCAT_INTERNALPROXIES
      value: ".*"
    - name: MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE
      value: "*"
    - name: "ACTIVITI_CLOUD_APPLICATION_NAME"
      value: "{{ .Release.Name }}"
    - name: ACT_RB_SERVICE_URL
      value: '{{ include "common.gateway-url" . }}/{{ .Release.Name }}/rb'

alfresco-process-workspace-app:
  enabled: false
  nameOverride: workspace-app
  image:
    repository: quay.io/alfresco/alfresco-process-workspace-app
    tag: 7.1.0.M6
  ingress:
    path: "/{{ .Release.Name }}/workspace"
  env:
    APP_CONFIG_AUTH_TYPE: "OAUTH"
    APP_CONFIG_BPM_HOST: '{{ include "common.gateway-url" . }}'
    APP_CONFIG_APPS_DEPLOYED: '[{"name": "{{ .Release.Name }}" }]'

alfresco-admin-app:
  enabled: false
  nameOverride: admin-app
  ingress:
    path: "/{{ .Release.Name }}/admin"
  image:
    repository: quay.io/alfresco/alfresco-admin-app
    tag: 7.1.0.M6
    pullPolicy: Always
  env:
    APP_CONFIG_BPM_HOST: '{{ include "common.gateway-url" . }}'
    APP_CONFIG_AUTH_TYPE: "OAUTH"
    APP_CONFIG_IDENTITY_HOST: '{{ include "common.keycloak-url" . }}/admin/realms/{{ include "common.keycloak-realm" . }}'
    APP_CONFIG_APPS_DEPLOYED: '[{"name": "{{ .Release.Name }}" }]'

postgres:
  enabled: true
  postgresqlPassword: password
  resources:
    requests:
      cpu: 350m
      memory: 512Mi

rabbitmq:
  enabled: true
  service:
    clusterIP: None
  persistentVolume:
    enabled: true
  rabbitmqUsername: "guest"
  rabbitmqPassword: "guest"
  rabbitmqErlangCookie: 124567890abcdefghijklmnopqrstuv
  rabbitmqSTOMPPlugin:
    enabled: true
  resources:
    limits:
      cpu: 1
      memory: 2Gi
    requests:
      cpu: 350m
      memory: 512Mi
  rbac:
    create: true
  replicaCount: 1
  ingress:
    enabled: false
    hostName: "REPLACEME"
    path: /rabbitmq
    annotations:
      kubernetes.io/ingress.class: nginx
      nginx.ingress.kubernetes.io/enable-cors: "true"
      nginx.ingress.kubernetes.io/cors-allow-headers: "*"
      nginx.ingress.kubernetes.io/x-forwarded-prefix: "true"

persistence:
  enabled: false

volumeinit:
  enabled: false
