# Default values for alfresco-process-application.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

global:
  ## Configure pull secrets for all deployments
  registryPullSecrets:
    - "quay-registry-secret"

  image:
    pullPolicy: "Always"

  keycloak:
    ## Configure Activiti Keycloak host template, i.e. "identity.{{ .Release.Namespace }}.{{ .Values.global.gateway.domain }}"
    host: 'identity.{{ include "common.gateway-domain" . }}'

    ## Set full url to configure external Keycloak, https://keycloak.mydomain.com/auth
    url: ""

    ## Configure Keycloak realm
    realm: "alfresco"
    resource: "activiti"
    client: "activiti"

  gateway:
    ## Set to configure single domain name for all services, i.e. "gateway.{{ .Release.Namespace }}.{{ .Values.global.gateway.domain }}"
    host: 'gateway.{{ include "common.gateway-domain" . }}'

    ## Set to false enables HTTPS configuration on all urls
    http: "true"

    ## Set to enable automatic TLS for ingress if https is enabled
    tlsacme: "true"

    ## Set to configure gateway domain template, i.e. {{ .Release.Namespace }}.1.3.4.5.nip.io
    #  helm upgrade activiti . --install --set global.gateway.domain=1.2.3.4.nip.io
    domain: "REPLACEME"

    ## Configure global annotations for all service ingresses, i.e.
    annotations:
      certmanager.k8s.io/issuer: "letsencrypt-prod"
      kubernetes.io/ingress.class: nginx
      nginx.ingress.kubernetes.io/enable-cors: "true"
      nginx.ingress.kubernetes.io/cors-allow-headers: "*"
      nginx.ingress.kubernetes.io/x-forwarded-prefix: "true"

  # Use Yaml formatted string to add extra environment properties to all deployments
  extraEnv: |
    - name: SERVER_USEFORWARDHEADERS
      value: "true"
    - name: SERVER_TOMCAT_INTERNALPROXIES
      value: ".*"
    - name: MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE
      value: "*"
    - name: KEYCLOAK_USERESOURCEROLEMAPPINGS
      value: "false"
    - name: "ACTIVITI_CLOUD_APPLICATION_NAME"
      value: "{{ .Release.Name }}"

activiti-cloud-query:
  enabled: true
  nameOverride: query
  postgres:
    enabled: true
  image:
    repository: quay.io/alfresco/alfresco-process-query-service
    tag: "7.1.0.M5"
  ingress:
    path: "/{{ .Release.Name }}/query"
    enabled: true
  probePath: "{{ tpl .Values.ingress.path . }}/actuator/health"
  extraEnv: |
    - name: SERVER_SERVLET_CONTEXTPATH
      value: "{{ tpl .Values.ingress.path . }}"
  extraVolumes: |
    - name: license
      secret:
        secretName: licenseaps
  extraVolumeMounts: |
    - name: license
      mountPath: "/root/.activiti/enterprise-license/"
      readOnly: true

activiti-cloud-audit:
  enabled: true
  nameOverride: audit
  postgres:
    enabled: true
  image:
    repository: quay.io/alfresco/alfresco-process-audit-service
    tag: "7.1.0.M5"
  ingress:
    enabled: true
    path: "/{{ .Release.Name }}/{{ .Values.nameOverride }}"
  probePath: "{{ tpl .Values.ingress.path . }}/actuator/health"
  extraEnv: |
    - name: SERVER_SERVLET_CONTEXTPATH
      value: "{{ tpl .Values.ingress.path . }}"
  extraVolumes: |
    - name: license
      secret:
        secretName: licenseaps
  extraVolumeMounts: |
    - name: license
      mountPath: "/root/.activiti/enterprise-license/"
      readOnly: true

runtime-bundle:
  enabled: true
  nameOverride: rb
  serviceAccount:
    create: false
  rbac:
    create: false
  postgres:
    enabled: true
  image:
    repository: activiti/example-runtime-bundle
    tag: "7.1.0.M5"
  ingress:
    enabled: true
    path: "/{{ .Release.Name }}/{{ .Values.nameOverride }}"
  probePath: "{{ tpl .Values.ingress.path . }}/actuator/health"
  extraEnv: |
    - name: SERVER_SERVLET_CONTEXTPATH
      value: "{{ tpl .Values.ingress.path . }}"
    - name: ACT_KEYCLOAK_RESOURCE
      value: "{{ .Release.Name }}"
    - name: KEYCLOAK_USERESOURCEROLEMAPPINGS
      value: "true"
  extraVolumes: |
    - name: license
      secret:
        secretName: licenseaps
  extraVolumeMounts: |
    - name: license
      mountPath: "/root/.activiti/enterprise-license/"
      readOnly: true

activiti-cloud-connector:
  enabled: false
  nameOverride: example-cloud-connector
  serviceAccount:
    create: false
  rbac:
    create: false
  image:
    repository: activiti/example-cloud-connector
    tag: "7.1.0.M5"
  ingress:
    enabled: true
    path: "/{{ .Release.Name }}/{{ .Values.nameOverride }}"
  probePath: "{{ tpl .Values.ingress.path . }}/actuator/health"
  extraEnv: |
    - name: SERVER_SERVLET_CONTEXTPATH
      value: "{{ tpl .Values.ingress.path . }}"

activiti-cloud-notifications-graphql:
  enabled: true
  nameOverride: notifications
  image:
    repository: quay.io/alfresco/alfresco-process-notifications-graphql-service
    tag: "7.1.0.M5"
  ingress:
    enabled: true
    path: "/{{ .Release.Name }}/notifications"

alfresco-dmn-service:
  enabled: true
  nameOverride: dmn
  rbac:
    create: false
  serviceAccount:
    create: false
  ingress:
    enabled: true
    path: "/{{ .Release.Name }}/{{ .Values.nameOverride }}/?(.*)"
    annotations:
      nginx.ingress.kubernetes.io/rewrite-target: /$1
  extraVolumes: |
    - name: license
      secret:
        secretName: licenseaps
  extraVolumeMounts: |
    - name: license
      mountPath: "/root/.activiti/enterprise-license/"
      readOnly: true
  image:
    repository: quay.io/alfresco/alfresco-dmn-runtime-service
    tag: "7.1.0.M5"
    pullPolicy: Always
  postgres:
    enabled: true
  probePath: "/{{ .Release.Name }}/{{ .Values.nameOverride }}/actuator/health"
  extraEnv: |
    - name: SERVER_PORT
      value: "8080"
    - name: SERVER_SERVLET_CONTEXTPATH
      value: "/{{ .Release.Name }}/{{ .Values.nameOverride }}"
    - name: ACT_RB_SERVICE_URL
      value: '{{ include "common.gateway-url" . }}/{{ .Release.Name }}/rb'

alfresco-form-service:
  enabled: true
  nameOverride: form
  rbac:
    create: false
  serviceAccount:
    create: false
  ingress:
    enabled: true
    path: "/{{ .Release.Name }}/{{ .Values.nameOverride }}/?(.*)"
    annotations:
      nginx.ingress.kubernetes.io/rewrite-target: /$1
  extraVolumes: |
    - name: license
      secret:
        secretName: licenseaps
  extraVolumeMounts: |
    - name: license
      mountPath: "/root/.activiti/enterprise-license/"
      readOnly: true
  image:
    repository: quay.io/alfresco/alfresco-form-service
    tag: "7.1.0.M5"
    pullPolicy: Always
  postgres:
    enabled: true
  probePath: "/{{ .Release.Name }}/{{ .Values.nameOverride }}/actuator/health"
  extraEnv: |
    - name: SERVER_PORT
      value: "8080"
    - name: SERVER_SERVLET_CONTEXTPATH
      value: "/{{ .Release.Name }}/{{ .Values.nameOverride }}"
    - name: ACT_RB_SERVICE_URL
      value: '{{ include "common.gateway-url" . }}/{{ .Release.Name }}/rb'

alfresco-preference-service:
  enabled: true
  nameOverride: preference
  rbac:
    create: false
  serviceAccount:
    create: false
  ingress:
    enabled: true
    path: "/{{ .Release.Name }}/{{ .Values.nameOverride }}/?(.*)"
    annotations:
      nginx.ingress.kubernetes.io/rewrite-target: /$1
  extraVolumes: |
    - name: license
      secret:
        secretName: licenseaps
  extraVolumeMounts: |
    - name: license
      mountPath: "/root/.activiti/enterprise-license/"
      readOnly: true
  image:
    repository: quay.io/alfresco/alfresco-preference-service
    tag: "7.1.0.M5"
    pullPolicy: Always
  postgres:
    enabled: true
  probePath: "/{{ .Release.Name }}/{{ .Values.nameOverride }}/actuator/health"
  extraEnv: |
    - name: SERVER_PORT
      value: "8080"
    - name: SERVER_SERVLET_CONTEXTPATH
      value: "/{{ .Release.Name }}/{{ .Values.nameOverride }}"

alfresco-process-workspace-app:
  enabled: false
  nameOverride: workspace-app
  image:
    repository: quay.io/alfresco/alfresco-process-workspace-app
    tag: "7.1.0.M5"
  ingress:
    path: "/{{ .Release.Name }}/workspace"
  env:
    APP_CONFIG_AUTH_TYPE: "OAUTH"
    APP_CONFIG_BPM_HOST: '{{ include "common.gateway-url" . }}'
    APP_CONFIG_APPS_DEPLOYED: '[{"name": "{{ .Release.Name }}" }]'

alfresco-admin-app:
  enabled: false
  nameOverride: admin-app
  ingress:
    path: "/{{ .Release.Name }}/admin"
  image:
    repository: quay.io/alfresco/alfresco-admin-app
    tag: "7.1.0.M5"
    pullPolicy: Always
  env:
    APP_CONFIG_BPM_HOST: '{{ include "common.gateway-url" . }}'
    APP_CONFIG_AUTH_TYPE: "OAUTH"
    APP_CONFIG_IDENTITY_HOST: '{{ include "common.keycloak-url" . }}/admin/realms/{{ include "common.keycloak-realm" . }}'
    APP_CONFIG_APPS_DEPLOYED: '[{"name": "{{ .Release.Name }}" }]'

postgres:
  enabled: true
  postgresqlPassword: password
  resources:
    requests:
      cpu: 350m
      memory: 512Mi

rabbitmq:
  enabled: true
  service:
    clusterIP: None
  persistentVolume:
    enabled: true
  rabbitmqUsername: "guest"
  rabbitmqPassword: "guest"
  rabbitmqErlangCookie: 124567890abcdefghijklmnopqrstuv
  rabbitmqSTOMPPlugin:
    enabled: true
  resources:
    limits:
      cpu: 1
      memory: 2Gi
    requests:
      cpu: 350m
      memory: 512Mi
  rbac:
    create: true
  replicaCount: 1
  ingress:
    enabled: false
    #hostName: "REPLACEME"
    path: /rabbitmq
    # annotations:
      # kubernetes.io/ingress.class: nginx
      # nginx.ingress.kubernetes.io/enable-cors: "true"
      # nginx.ingress.kubernetes.io/cors-allow-headers: "*"
      # nginx.ingress.kubernetes.io/x-forwarded-prefix: "true"
