image: alpine:latest

variables:
  HELM_VERSION: 2.9.1

stages:
- deploy

.deploy_chart: &deploy_chart
  stage: deploy
  variables:
    CHART_REPO_FOLDER: incubator
  script:
    - install_dependencies
    - setup_git
    - setup_build_helm_tools
    - export helm_chart_repo="http://kubernetes-charts.alfresco.com/${CHART_REPO_FOLDER}/"
    - export git_repo='git@github.com:Alfresco/charts.git'
    - export git_repo_subdir="${CHART_REPO_FOLDER}"
    - export chart_source_dirs='helm/alfresco-process-infrastructure'
    - ${HELM_TOOLS_HOME}/bin/helm-updater.sh

deploy_chart_incubator:
  variables:
    CHART_REPO_FOLDER: incubator
  <<: *deploy_chart
  only:
    refs:
      - develop

deploy_chart_stable:
  variables:
    CHART_REPO_FOLDER: stable
  <<: *deploy_chart
  only:
    refs:
      - master

.declare_functions: &declare_functions |

  function install_dependencies() {
    apk add -U openssl curl tar gzip bash ca-certificates git openssh
    wget -q -O /etc/apk/keys/sgerrand.rsa.pub https://alpine-pkgs.sgerrand.com/sgerrand.rsa.pub
    wget https://github.com/sgerrand/alpine-pkg-glibc/releases/download/2.23-r3/glibc-2.23-r3.apk
    apk add glibc-2.23-r3.apk
    rm glibc-2.23-r3.apk

    curl "https://kubernetes-helm.storage.googleapis.com/helm-v${HELM_VERSION}-linux-amd64.tar.gz" | tar zx
    mv linux-amd64/helm /usr/bin/
    helm version --client
  }

  function setup_git() {
    git clone --depth 1 https://$GITLAB_USER:$GITLAB_PASSWORD@git.alfresco.com/Build/bamboo-agent-config.git
    mkdir ~/.ssh
    cp ./bamboo-agent-config/keys/idgit_rsa ~/.ssh/id_rsa
    chmod 400 ~/.ssh/id_rsa
    git config --global user.name "alfresco-build"
    git config --global user.email "alfresco-build@alfresco.com"
    export GIT_SSH_COMMAND="ssh -i ~/.ssh/id_rsa"
    ssh-keyscan github.com >> ~/.ssh/known_hosts
  }

  function setup_build_helm_tools() {
    git clone --depth 1 https://$GITLAB_USER:$GITLAB_PASSWORD@git.alfresco.com/platform-services/bamboo-build-helm-tools.git
    export HELM_TOOLS_HOME="./bamboo-build-helm-tools"
  }

before_script:
  - *declare_functions
