repos:
  - repo: https://github.com/norwoodj/helm-docs
    rev: v1.3.0
    hooks:
      - id: helm-docs
  - repo: https://github.com/Alfresco/alfresco-process-tools
    rev: 62e8804
    hooks:
      - id: travis-yml-lint
      - id: helm-deps
      - id: helm-lint
      - id: kubepug-minimum
      - id: kubepug-recommended
