repos:
  - repo: https://github.com/norwoodj/helm-docs
    rev: 88016b1dd49783a8bbb44d624742fa9554bfe86f # frozen: v1.10.0
    hooks:
      - id: helm-docs
  - repo: https://github.com/Alfresco/alfresco-build-tools
    rev: 567a9393acca033008ce34eafcb200469e4ea2f5 # frozen: v18.27.0
    hooks:
      - id: helm-deps
      - id: helm-lint
      - id: kubepug-minimum
      - id: kubepug-recommended
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 3298ddab3c13dd77d6ce1fc0baf97691430d84b0 # frozen: v4.3.0
    hooks:
      - id: check-yaml
        args: [--allow-multiple-documents]
        exclude: helm/.*/templates
      - id: check-json
      - id: check-merge-conflict
      - id: fix-byte-order-marker
      - id: mixed-line-ending
        args: ['--fix=lf']
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/sirosen/check-jsonschema
    rev: 098aa5b45336ea3d50a31b093c3194f33b59307b # frozen: 0.17.0
    hooks:
      - id: check-github-workflows
      - id: check-jsonschema
        alias: check-dependabot
        name: "Validate Dependabot Config"
        files: '.github/dependabot\.yml$'
        args: ["--schemafile", "https://json.schemastore.org/dependabot-2.0.json"]
