language: generic

env:
  global:
    - HELM_VERSION=2.9.1
    - HELM_REPO_BASE_URL=http://kubernetes-charts.alfresco.com
    - HELM_REPO=stable

install: |
  curl https://kubernetes-helm.storage.googleapis.com/helm-v${HELM_VERSION}-linux-amd64.tar.gz | tar zx
  sudo mv linux-amd64/helm /usr/local/bin/

branches:
  only:
    - master
    - develop

stages:
  - name: build
    if: branch IN (master, develop)

before_script: |
  PROJECT_NAME=${TRAVIS_REPO_SLUG}
  PROJECT_NAME=${PROJECT_NAME##*/}
  PROJECT_NAME=${PROJECT_NAME%%-deployment}
  echo using PROJECT_NAME=${PROJECT_NAME}
  helm init --client-only
  helm repo add activiti https://activiti.github.io/activiti-cloud-helm-charts
  helm repo add alfresco https://kubernetes-charts.alfresco.com/stable
  [[ "${TRAVIS_BRANCH}" == 'develop' ]] && helm repo add alfresco-incubator https://kubernetes-charts.alfresco.com/incubator

jobs:
  include:
    - name: package and publish chart
      stage: build
      script: |
        COMMIT_MESSAGE_FIRST_LINE=$(git log --pretty=format:%s --max-count=1)
        echo using COMMIT_MESSAGE_FIRST_LINE=${COMMIT_MESSAGE_FIRST_LINE}
        helm lint helm/${PROJECT_NAME}
        git clone https://${GITHUB_TOKEN}@github.com/Alfresco/charts.git
        [[ "${TRAVIS_BRANCH}" == 'develop' ]] && HELM_REPO=incubator
        echo using HELM_REPO=${HELM_REPO}
        mkdir repo
        helm package --dependency-update --destination repo helm/${PROJECT_NAME}
        helm repo index repo --url ${HELM_REPO_BASE_URL}/${HELM_REPO} --merge charts/${HELM_REPO}/index.yaml
        mv repo/* charts/${HELM_REPO}
        cd charts
        git config --global user.email "alfresco-build@alfresco.com"
        git config --global user.name "alfresco-build"
        git commit -am "${COMMIT_MESSAGE_FIRST_LINE}"
        git push --quiet origin master
