alfresco-content-services:
  externalProtocol: "http"
  externalHost: "host.docker.internal"
  repository:
    environment:
      IDENTITY_SERVICE_URI: "http://host.docker.internal/auth"
    livenessProbe:
      initialDelaySeconds: 420
    readinessProbe:
      initialDelaySeconds: 500
    resources:
      requests:
        memory: "1800Mi"
  share:
    replicaCount: 0
  alfresco-digital-workspace:
    APP_CONFIG_OAUTH2_HOST: "http://host.docker.internal/auth/realms/alfresco"
    APP_CONFIG_OAUTH2_REDIRECT_SILENT_IFRAME_URI: "http://host.docker.internal/digital-workspace/assets/silent-refresh.html"
  pdfrenderer:
    replicaCount: 0
  libreoffice:
    replicaCount: 0
  imagemagick:
    replicaCount: 0
  transformrouter:
    replicaCount: 0
  tika:
    replicaCount: 0
  filestore:
    replicaCount: 0
