runtime-bundle:
  image:
    repository: mteodori/beerer-runtime-bundle
    tag: latest
    pullPolicy: Always
activiti-cloud-connector:
  image:
    repository: mteodori/untappd-cloud-connector
    tag: latest
    pullPolicy: Always
  extraEnv: |
    - name: UNTAPPD_API_CLIENT_ID
      value: "51B5BAED65B9556BB46B0F1788E83A13A8E22C19"
    - name: UNTAPPD_API_CLIENT_SECRET
      value: "2843392EFC7BA90B8747A754B6201410B1A8CD1D"
