# helm upgrade --reuse-values $HELM_OPTS activiti-cloud-full-example activiti-cloud-charts/activiti-cloud-full-example --debug --dry-run

global:
  keycloak:
    url: "https://activiti-keycloak.aps2pentest.envalfresco.com/auth"
  gateway:
    host: &gatewayhost activiti-cloud-gateway.aps2pentest.envalfresco.com

infrastructure:
  activiti-keycloak:
    keycloak:
      keycloak:
        ingress:
          hosts:
            - "activiti-keycloak.aps2pentest.envalfresco.com"


activiti-cloud-modeling:
  enabled: true
  backend:
    url: "https://activiti-cloud-gateway.aps2pentest.envalfresco.com"
