global:
  keycloak:
    url: "https://activiti-keycloak.REPLACEME/auth"
    realm: activiti
  gateway:
    host: &gatewayhost "activiti-cloud-gateway.REPLACEME"
  ingress-annotations: &ingress-annotations
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/enable-cors: true
    nginx.ingress.kubernetes.io/cors-allow-headers: "*"
    nginx.ingress.kubernetes.io/x-forwarded-prefix: true
