activiti-cloud-query:
  enabled: true
  db:
    deployPostgres: true
  ingress:
    enabled: true
    path: "/{{ .Release.Name }}-query"
    annotations:
      nginx.ingress.kubernetes.io/rewrite-target: "null"
  probePath: "/{{ .Release.Name }}-query/actuator/health"
  extraEnv: |
    - name: KEYCLOAK_USERESOURCEROLEMAPPINGS
      value: "false"
    - name: SERVER_SERVLET_CONTEXTPATH
      value: "/{{ .Release.Name }}-query"
    - name: SERVER_USEFORWARDHEADERS
      value: "true"
    - name: SERVER_TOMCAT_INTERNALPROXIES
      value: ".*"
    - name: MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE
      value: "*"

activiti-cloud-audit:
  enabled: true
  db:
    deployPostgres: true
  ingress:
    enabled: true
    path: "/{{ .Release.Name }}-audit"
    annotations:
      nginx.ingress.kubernetes.io/rewrite-target: "null"
  probePath: "/{{ .Release.Name }}-audit/actuator/health"
  extraEnv: |
    - name: KEYCLOAK_USERESOURCEROLEMAPPINGS
      value: "false"
    - name: SERVER_SERVLET_CONTEXTPATH
      value: "/{{ .Release.Name }}-audit"
    - name: SERVER_USEFORWARDHEADERS
      value: "true"
    - name: SERVER_TOMCAT_INTERNALPROXIES
      value: ".*"
    - name: MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE
      value: "*"

runtime-bundle:
  enabled: true
  db:
    deployPostgres: true
  ingress:
    enabled: true
    path: "/{{ .Release.Name }}-rb"
    annotations:
      nginx.ingress.kubernetes.io/rewrite-target: "null"
  probePath: "/{{ .Release.Name }}-rb/actuator/health"
  extraEnv: |
    - name: KEYCLOAK_USERESOURCEROLEMAPPINGS
      value: "false"
    - name: SERVER_SERVLET_CONTEXTPATH
      value: "/{{ .Release.Name }}-rb"
    - name: SERVER_USEFORWARDHEADERS
      value: "true"
    - name: SERVER_TOMCAT_INTERNALPROXIES
      value: ".*"
    - name: MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE
      value: "*"

activiti-cloud-connector:
  enabled: true
  ingress:
    enabled: true
    path: "/{{ .Release.Name }}-example-cloud-connector"
    annotations:
      nginx.ingress.kubernetes.io/rewrite-target: "null"
  probePath: "/{{ .Release.Name }}-example-cloud-connector/actuator/health"
  extraEnv: |
    - name: KEYCLOAK_USERESOURCEROLEMAPPINGS
      value: "false"
    - name: SERVER_SERVLET_CONTEXTPATH
      value: "/{{ .Release.Name }}-example-cloud-connector"
    - name: SERVER_USEFORWARDHEADERS
      value: "true"
    - name: SERVER_TOMCAT_INTERNALPROXIES
      value: ".*"
    - name: MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE
      value: "*"

activiti-cloud-notifications-graphql:
  enabled: true
  ingress:
    # path: "/{{ .Release.Name }}"
    enabled: true
  extraEnv: |
    - name: KEYCLOAK_USERESOURCEROLEMAPPINGS
      value: "false"
    - name: SERVER_USEFORWARDHEADERS
      value: "true"
    - name: SERVER_TOMCAT_INTERNALPROXIES
      value: ".*"
    - name: MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE
      value: "*"
