global:
  keycloak:
    url: "${SSO_URL}"
    realm: "${REALM}"
  gateway:
    host: "${GATEWAY_HOST}"
    ingress:
      annotations: &ingress-annotations
        kubernetes.io/ingress.class: nginx
        nginx.ingress.kubernetes.io/enable-cors: "true"
        nginx.ingress.kubernetes.io/cors-allow-headers: "*"

activiti-cloud-query:
  enabled: true
  db:
    deployPostgres: true
  service:
    name: "{{ .Release.Name }}-query"
  ingress:
    enabled: true
    path: "/{{ .Release.Name }}-query"
    annotations: *ingress-annotations
  probePath: "/{{ .Release.Name }}-query/actuator/health"
  extraEnv: |
    - name: SERVER_SERVLET_CONTEXTPATH
      value: "/{{ .Release.Name }}-query"
    - name: SERVER_USEFORWARDHEADERS
      value: "true"
    - name: SERVER_TOMCAT_INTERNALPROXIES
      value: ".*"
    - name: KEYCLOAK_REALM
      value: "${REALM}"
    - name: KEYCLOAK_USERESOURCEROLEMAPPINGS
      value: "false"
    - name: MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE
      value: "*"

activiti-cloud-audit:
  enabled: true
  db:
    deployPostgres: true
  service:
    name: "{{ .Release.Name }}-audit"
  ingress:
    enabled: true
    path: "/{{ .Release.Name }}-audit"
    annotations: *ingress-annotations
  probePath: "/{{ .Release.Name }}-audit/actuator/health"
  extraEnv: |
    - name: SERVER_SERVLET_CONTEXTPATH
      value: "/{{ .Release.Name }}-audit"
    - name: SERVER_USEFORWARDHEADERS
      value: "true"
    - name: SERVER_TOMCAT_INTERNALPROXIES
      value: ".*"
    - name: KEYCLOAK_REALM
      value: "${REALM}"
    - name: KEYCLOAK_USERESOURCEROLEMAPPINGS
      value: "false"
    - name: MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE
      value: "*"

runtime-bundle:
  enabled: true
  db:
    deployPostgres: true
  service:
    name: "{{ .Release.Name }}-rb"
  ingress:
    enabled: true
    path: "/{{ .Release.Name }}-rb"
    annotations: *ingress-annotations
  probePath: "/{{ .Release.Name }}-rb/actuator/health"
  serviceAccount:
    create: false
  rbac:
    create: false
  extraEnv: |
    - name: SERVER_SERVLET_CONTEXTPATH
      value: "/{{ .Release.Name }}-rb"
    - name: SERVER_USEFORWARDHEADERS
      value: "true"
    - name: SERVER_TOMCAT_INTERNALPROXIES
      value: ".*"
    - name: KEYCLOAK_REALM
      value: "${REALM}"
    - name: KEYCLOAK_USERESOURCEROLEMAPPINGS
      value: "false"
    - name: MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE
      value: "*"

activiti-cloud-connector:
  enabled: true
  service:
    name: "{{ .Release.Name }}-example-cloud-connector"
  ingress:
    enabled: true
    path: "/{{ .Release.Name }}-example-cloud-connector"
    annotations: *ingress-annotations
  probePath: "/{{ .Release.Name }}-example-cloud-connector/actuator/health"
  serviceAccount:
    create: false
  rbac:
    create: false
  extraEnv: |
    - name: SERVER_SERVLET_CONTEXTPATH
      value: "/{{ .Release.Name }}-example-cloud-connector"
    - name: SERVER_USEFORWARDHEADERS
      value: "true"
    - name: SERVER_TOMCAT_INTERNALPROXIES
      value: ".*"
    - name: KEYCLOAK_REALM
      value: "${REALM}"
    - name: KEYCLOAK_USERESOURCEROLEMAPPINGS
      value: "false"
    - name: MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE
      value: "*"

activiti-cloud-notifications-graphql:
  enabled: false
  service:
    name: "{{ .Release.Name }}-activiti-cloud-notifications"
  extraEnv: |
    - name: SERVER_USEFORWARDHEADERS
      value: "true"
    - name: SERVER_TOMCAT_INTERNALPROXIES
      value: ".*"
    - name: KEYCLOAK_REALM
      value: "${REALM}"
    - name: KEYCLOAK_USERESOURCEROLEMAPPINGS
      value: "false"
    - name: MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE
      value: "*"
