
global:
  ## Configure pull secrets for all deployments
  registryPullSecrets: 
  - "quay-registry-secret"

  keycloak:
    ## Configure Activiti Keycloak host template, i.e. "activiti-keycloak.{{ .Release.Namespace }}.{{ .Values.global.gateway.domain }}"
    host: "activiti-keycloak.{{ .Values.global.gateway.domain }}"

    ## Set full url to configure external Keycloak, https://keycloak.mydomain.com/auth
    url: ""

    ## Configure Keycloak realm
    realm: "alfresco"
    resource: "activiti"
    client: "activiti"

  gateway:
    ## Set to configure single domain name for all services, i.e. "activiti-cloud-gateway.{{ .Release.Namespace }}.{{ .Values.global.gateway.domain }}"
    host: "activiti-cloud-gateway.{{ .Values.global.gateway.domain }}"

    ## Set to false enables HTTPS configuration on all urls 
    http: "true"

    ## Set to enable automatic TLS for ingress if https is enabled
    tlsacme: "false"

    ## Set to configure gateway domain template, i.e. {{ .Release.Namespace }}.1.3.4.5.nip.io
    #  helm upgrade activiti . --install --set global.gateway.domain=1.2.3.4.nip.io
    domain: "REPLACEME"

    ## Configure global annotations for all service ingresses, i.e. 
    annotations: 
      certmanager.k8s.io/issuer: "letsencrypt-prod"

activiti-cloud-modeling:
  enabled: true
  db:
    deployPostgres: true
  ingress:
    enabled: true
  extraEnv: |
    - name: KEYCLOAK_REALM
      value: "{{ .Values.global.keycloak.realm }}"
    - name: SERVER_SERVLET_CONTEXTPATH
      value: /activiti-cloud-modeling

activiti-cloud-query:
  db:
    deployPostgres: true
  image:
    repository: quay.io/alfresco/alfresco-process-query-service
    tag: develop
    pullPolicy: Always
  ingress:
    path: "/{{ .Release.Name }}/query"
    enabled: true
  extraEnv: |
    - name: KEYCLOAK_REALM
      value: "{{ .Values.global.keycloak.realm }}"
    - name: KEYCLOAK_USERESOURCEROLEMAPPINGS
      value: "false"
activiti-cloud-audit:
  db:
    deployPostgres: true
  image:
    repository: quay.io/alfresco/alfresco-process-audit-service
    tag: develop
    pullPolicy: Always
  ingress:
    path: "/{{ .Release.Name }}/audit"
    enabled: true
  extraEnv: |
    - name: KEYCLOAK_REALM
      value: "{{ .Values.global.keycloak.realm }}"
    - name: KEYCLOAK_USERESOURCEROLEMAPPINGS
      value: "false"
runtime-bundle:
  db:
    deployPostgres: true
  image:
    repository: quay.io/alfresco/alfresco-example-process-runtime-bundle-service
    tag: develop
    pullPolicy: Always
  extraEnv: |
    - name: KEYCLOAK_REALM
      value: "{{ .Values.global.keycloak.realm }}"
    - name: KEYCLOAK_USERESOURCEROLEMAPPINGS
      value: "false"
  ingress:
    path: "/{{ .Release.Name }}/rb"
    enabled: true
  extraVolumes: |
    - name: license
      secret:
        secretName: licenseaps
  extraVolumeMounts: |
    - name: license
      mountPath: "/root/.activiti/enterprise-license/"
      readOnly: true
activiti-cloud-connector:
  enabled: true
  ingress:
    enabled: true
    path: "/{{ .Release.Name }}/example-cloud-connector"

activiti-cloud-notifications-graphql:
  enabled: true
  ingress:
    # path: "/{{ .Release.Name }}"
    enabled: true
