activiti-cloud-modeling:
  enabled: true
  db:
    deployPostgres: true
  ingress:
    enabled: true
  extraEnv: |
    - name: KEYCLOAK_REALM
      value: "{{ .Values.global.keycloak.realm }}"
    - name: SERVER_SERVLET_CONTEXTPATH
      value: /activiti-cloud-modeling

activiti-cloud-query:
  db:
    deployPostgres: true
  image:
    repository: quay.io/alfresco/alfresco-process-query-service
    tag: develop
    pullPolicy: Always
  ingress:
    path: "/{{ .Release.Name }}-query"
    enabled: true
  extraEnv: |
    - name: KEYCLOAK_REALM
      value: "{{ .Values.global.keycloak.realm }}"
    - name: KEYCLOAK_USERESOURCEROLEMAPPINGS
      value: "false"
activiti-cloud-audit:
  db:
    deployPostgres: true
  image:
    repository: quay.io/alfresco/alfresco-process-audit-service
    tag: develop
    pullPolicy: Always
  ingress:
    enabled: true
    path: "/{{ .Release.Name }}-audit"
    annotations:
      nginx.ingress.kubernetes.io/rewrite-target: "/" # TODO: fix in the base chart
  extraEnv: |
    - name: KEYCLOAK_REALM
      value: "{{ .Values.global.keycloak.realm }}"
    - name: KEYCLOAK_USERESOURCEROLEMAPPINGS
      value: "false"
runtime-bundle:
  db:
    deployPostgres: true
  image:
    repository: quay.io/alfresco/alfresco-example-process-runtime-bundle-service
    tag: develop
    pullPolicy: Always
  ingress:
    enabled: true
    path: "/{{ .Release.Name }}-rb"
  extraEnv: |
    - name: KEYCLOAK_REALM
      value: "{{ .Values.global.keycloak.realm }}"
    - name: KEYCLOAK_USERESOURCEROLEMAPPINGS
      value: "false"
  extraVolumes: |
    - name: license
      secret:
        secretName: licenseaps
  extraVolumeMounts: |
    - name: license
      mountPath: "/root/.activiti/enterprise-license/"
      readOnly: true
activiti-cloud-connector:
  enabled: true
  ingress:
    enabled: true
    path: "/{{ .Release.Name }}-example-cloud-connector"

activiti-cloud-notifications-graphql:
  enabled: true
  ingress:
    # path: "/{{ .Release.Name }}"
    enabled: true
