activiti-cloud-query:
  db:
    deployPostgres: true
  image:
    repository: quay.io/alfresco/alfresco-process-query-service
    tag: develop
    pullPolicy: Always
  ingress:
    path: "/{{ .Release.Name }}-query"
    enabled: true
    annotations:
      nginx.ingress.kubernetes.io/rewrite-target: "null"
  probePath: "/{{ .Release.Name }}-query/actuator/health"
  extraEnv: |
    - name: SERVER_SERVLET_CONTEXTPATH
      value: "/{{ .Release.Name }}-query"

activiti-cloud-audit:
  db:
    deployPostgres: true
  image:
    repository: quay.io/alfresco/alfresco-process-audit-service
    tag: develop
    pullPolicy: Always
  ingress:
    enabled: true
    path: "/{{ .Release.Name }}-audit"
    annotations:
      nginx.ingress.kubernetes.io/rewrite-target: "null"
  probePath: "/{{ .Release.Name }}-audit/actuator/health"
  extraEnv: |
    - name: SERVER_SERVLET_CONTEXTPATH
      value: "/{{ .Release.Name }}-audit"

runtime-bundle:
  service:
    name: rb-my-app  
  db:
    deployPostgres: true
  image:
    repository: quay.io/alfresco/alfresco-example-process-runtime-bundle-service
    tag: develop
    pullPolicy: Always
  ingress:
    enabled: true
    path: "/{{ .Release.Name }}-rb"
    annotations:
      nginx.ingress.kubernetes.io/rewrite-target: "null"
  probePath: "/{{ .Release.Name }}-rb/actuator/health"
  extraEnv: |
    - name: SERVER_SERVLET_CONTEXTPATH
      value: "/{{ .Release.Name }}-rb"
  extraVolumes: |
    - name: license
      secret:
        secretName: licenseaps
  extraVolumeMounts: |
    - name: license
      mountPath: "/root/.activiti/enterprise-license/"
      readOnly: true

activiti-cloud-connector:
  enabled: true
  ingress:
    enabled: true
    path: "/{{ .Release.Name }}-example-cloud-connector"
    annotations:
      nginx.ingress.kubernetes.io/rewrite-target: "null"
  probePath: "/{{ .Release.Name }}-example-cloud-connector/actuator/health"
  extraEnv: |
    - name: SERVER_SERVLET_CONTEXTPATH
      value: "/{{ .Release.Name }}-example-cloud-connector"

activiti-cloud-notifications-graphql:
  enabled: true
  ingress:
    # path: "/{{ .Release.Name }}" # TODO fix graphiql app configuration 
    enabled: true
  # probePath: "/{{ .Release.Name }}/actuator/health"
  # extraEnv: |
  #   - name: SERVER_SERVLET_CONTEXTPATH
  #     value: "/{{ .Release.Name }}"
