global:
  gateway:
    host: "localhost"
    http: true
  keycloak:
    host: "host.docker.internal"

alfresco-content-services: &alfresco-content-services
  externalHost: &alfresco-content-services-external-host "localhost"
  externalProtocol: &alfresco-content-services-external-protocol "http"
  repository: &alfresco-content-services-repository
    livenessProbe:
      initialDelaySeconds: 420
    readinessProbe:
      initialDelaySeconds: 500
    resources:
      requests:
        memory: "1800Mi"
  share: &alfresco-content-services-share
    replicaCount: 0
    livenessProbe:
      initialDelaySeconds: 420
    readinessProbe:
      initialDelaySeconds: 500
    resources:
      requests:
        memory: "1800Mi"
  pdfrenderer:
    replicaCount: 0
  libreoffice:
    replicaCount: 0
  imagemagick:
    replicaCount: 0
  transformrouter:
    replicaCount: 0
  tika:
    replicaCount: 0
  filestore:
    replicaCount: 0

alfresco-content-services-community:
  externalHost: *alfresco-content-services-external-host
  externalProtocol: *alfresco-content-services-external-protocol
  repository: *alfresco-content-services-repository
  share: *alfresco-content-services-share
