keycloak:
  keycloak:
    ingress:
      hosts:
        - activiti-keycloak.aps2pentest.envalfresco.com
    image:
      repository: quay.io/alfresco/keycloak
      tag: 4.8.3.Final
    extraArgs: "-Dkeycloak.import=/realm/activiti-realm.json"
