activiti-cloud-query:
  image:
    repository: quay.io/alfresco/alfresco-process-query-service
  ingress:
    enabled: true
    path: "/{{ .Release.Name }}/query"
  probePath: "/{{ .Release.Name }}/query/actuator/health"
  extraEnv: |
    - name: KEYCLOAK_USERESOURCEROLEMAPPINGS
      value: "false"
    - name: SERVER_SERVLET_CONTEXTPATH
      value: "/{{ .Release.Name }}/query"

activiti-cloud-audit:
  image:
    repository: quay.io/alfresco/alfresco-process-audit-service
  ingress:
    enabled: true
    path: "/{{ .Release.Name }}/audit"
  probePath: "/{{ .Release.Name }}/audit/actuator/health"
  extraEnv: |
    - name: KEYCLOAK_USERESOURCEROLEMAPPINGS
      value: "false"
    - name: SERVER_SERVLET_CONTEXTPATH
      value: "/{{ .Release.Name }}/audit"

activiti-cloud-notifications-graphql:
  enabled: true
  image:
    repository: quay.io/alfresco/alfresco-cloud-notifications-graphql-service
  ingress:
    enabled: true
    path: "/{{ .Release.Name }}"
  probePath: "/{{ .Release.Name }}/actuator/health"
  extraEnv: |
    - name: SERVER_SERVLET_CONTEXTPATH
      value: "/{{ .Release.Name }}"

runtime-bundle:
  nameOverride: rb
  image:
    repository: quay.io/alfresco/alfresco-example-process-runtime-bundle-service
  ingress:
    enabled: true
    path: "/{{ .Release.Name }}/rb"
  probePath: "/{{ .Release.Name }}/rb/actuator/health"
  extraEnv: |
    - name: KEYCLOAK_USERESOURCEROLEMAPPINGS
      value: "true"
    - name: SERVER_SERVLET_CONTEXTPATH
      value: "/{{ .Release.Name }}/rb"
  extraVolumes: |
    - name: license
      secret:
        secretName: licenseaps
  extraVolumeMounts: |
    - name: license
      mountPath: "/root/.activiti/enterprise-license/"
      readOnly: true

activiti-cloud-connector:
  enabled: true
  ingress:
    enabled: true
    path: "/{{ .Release.Name }}/example-cloud-connector"
  probePath: "/{{ .Release.Name }}/example-cloud-connector/actuator/health"
  extraEnv: |
    - name: SERVER_SERVLET_CONTEXTPATH
      value: "/{{ .Release.Name }}/example-cloud-connector"

