# Default values for chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

alfresco-infrastructure:
  enabled: false
  rabbitmq-ha:
    enabled: false
  activemq:
    enabled: false
  alfresco-activiti-cloud-registry:
    enabled: false
  alfresco-api-gateway:
    enabled: false
  nginx-ingress:
    enabled: false
    controller:
      scope:
        enabled: false
      config:
        ssl-redirect: "false"
        use-proxy-protocol: "false"
  alfresco-identity-service:
    enabled: false
    keycloak:
      keycloak:
        image:
          tag: 4.6.0.Final
        extraArgs: "-Dkeycloak.import=/realm/alfresco-aps-realm.json"

alfresco-content-services:
  enabled: false
  networkpolicysetting:
    enabled: false
  registryPullSecrets: quay-registry-secret
  alfresco-infrastructure:
    enabled: false
    rabbitmq-ha:
      enabled: false
    activemq:
      enabled: false
    alfresco-activiti-cloud-registry:
      enabled: false
    alfresco-api-gateway:
      enabled: false
    nginx-ingress:
      enabled: false
    alfresco-identity-service:
      enabled: false
  share:
    CATALINA_OPTS: "
      -Dcsrf.filter.enabled=false
      -Xms1000M -Xmx1000M
      "
  repository:
    replicaCount: 1
    environment:
      # The IDENTITY_SERVICE_URI should contain the details of the ingress host and port.
      IDENTITY_SERVICE_URI: "<ingresscontrollerurl>/auth"
      IDENTITY_SERVICE_REALM: "alfresco"
      IDENTITY_SERVICE_RESOURCE: "activiti"
      JAVA_OPTS: "
        -Dsolr.base.url=/solr
        -Dsolr.secureComms=none
        -Dindex.subsystem.name=solr6
        -Ddeployment.method=HELM_CHART
        -Xms2000M -Xmx2000M
        -Dauthentication.chain=identity-service1:identity-service,alfrescoNtlm1:alfrescoNtlm
        -Didentity-service.enable-basic-auth=true
        -Didentity-service.authentication.validation.failure.silent=false
        -Didentity-service.auth-server-url=\"$IDENTITY_SERVICE_URI\"
        -Didentity-service.realm=\"$IDENTITY_SERVICE_REALM\"
        -Didentity-service.resource=\"$IDENTITY_SERVICE_RESOURCE\"
        -Dcsrf.filter.enabled=false
        "
