# Default values for chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

global:
  ## Configure pull secrets for all deployments
  registryPullSecrets:
    - "quay-registry-secret"

  keycloak:
    ## Configure Activiti Keycloak host template, i.e. "activiti-keycloak.{{ .Release.Namespace }}.{{ .Values.global.gateway.domain }}"
    #    host: "activiti-keycloak.{{ .Values.global.gateway.domain }}"

    ## Set full url to configure external Keycloak, https://keycloak.mydomain.com/auth
    url: ""

    ## Configure Keycloak realm
    realm: "alfresco"
    resource: "activiti"
    client: "activiti"

  gateway:
    ## Set to configure single domain name for all services, i.e. "activiti-cloud-gateway.{{ .Release.Namespace }}.{{ .Values.global.gateway.domain }}"
    #    host: "activiti-cloud-gateway.{{ .Values.global.gateway.domain }}"

    ## Set to false enables HTTPS configuration on all urls
    http: "false"

    ## Set to enable automatic TLS for ingress if https is enabled
    tlsacme: "false"

    ## Set to configure gateway domain template, i.e. {{ .Release.Namespace }}.1.3.4.5.nip.io
    #  helm upgrade activiti . --install --set global.gateway.domain=1.2.3.4.nip.io
    domain: "REPLACEME"

    ## Configure global annotations for all service ingresses, i.e.
    annotations:
      certmanager.k8s.io/issuer: "letsencrypt-prod"
      kubernetes.io/ingress.class: nginx
      nginx.ingress.kubernetes.io/enable-cors: "true"
      nginx.ingress.kubernetes.io/cors-allow-headers: "*"
      nginx.ingress.kubernetes.io/x-forwarded-prefix: "true"

alfresco-infrastructure:
  enabled: true
  alfresco-event-gateway:
    enabled: false
  # patch for https://issues.alfresco.com/jira/browse/DEPLOY-673
  activemq:
    image:
      tag: 5.15.6-java-8-oracle-centos-7-ac5b98b35cd4
  nginx-ingress:
    enabled: false
    controller:
      scope:
        enabled: false
  alfresco-identity-service:
    enabled: true
    keycloak:
      keycloak:
        extraArgs: "-Dkeycloak.import=/realm/alfresco-aps-realm.json"
    realm:
      alfresco:
        client:
          redirectUris:
            - "*"
          webOrigins:
            - "*"

alfresco-content-services:
  enabled: false
  registryPullSecrets: quay-registry-secret
  messageBroker:
    url:
    user: admin
    password: admin
  alfresco-infrastructure: &alfresco-content-services-alfresco-infrastructure
    enabled: false
    activemq:
      enabled: false
  networkpolicysetting:
    enabled: false
  repository: &alfresco-content-services-repository
    replicaCount: 1
    ingress:
      path: "/alfresco"
    environment:
      IDENTITY_SERVICE_URI: "https://alfresco-identity-service.REPLACEME/auth"
      IDENTITY_SERVICE_REALM: "alfresco"
      IDENTITY_SERVICE_RESOURCE: "activiti"
      JAVA_OPTS: "
        -Dsolr.base.url=/solr
        -Dsolr.secureComms=none
        -Dindex.subsystem.name=solr6
        -Dalfresco.cluster.enabled=true
        -Ddeployment.method=HELM_CHART
        -Xms1800M -Xmx1800M
        -Dauthentication.chain=identity-service1:identity-service,alfrescoNtlm1:alfrescoNtlm
        -Didentity-service.enable-basic-auth=true
        -Didentity-service.authentication.validation.failure.silent=false
        -Didentity-service.auth-server-url=\"$IDENTITY_SERVICE_URI\"
        -Didentity-service.realm=\"$IDENTITY_SERVICE_REALM\"
        -Didentity-service.resource=\"$IDENTITY_SERVICE_RESOURCE\"
        -Dlocal.transform.service.enabled=false
        -Dtransform.service.enabled=false
      "
  imagemagick:
    replicaCount: 1
  libreoffice:
    replicaCount: 1
  pdfrenderer:
    replicaCount: 1
  tika:
    replicaCount: 1
  transformrouter:
    replicaCount: 1
  alfresco-digital-workspace:
    networkpolicysetting:
      enabled: false
    APP_CONFIG_AUTH_TYPE: "OAUTH"
    APP_CONFIG_OAUTH2_HOST: "https://alfresco-identity-service.REPLACEME/auth/realms/alfresco"
    APP_CONFIG_OAUTH2_REDIRECT_LOGIN: "/workspace/"
    APP_CONFIG_OAUTH2_REDIRECT_LOGOUT: "/workspace/logout"
    APP_CONFIG_OAUTH2_REDIRECT_SILENT_IFRAME_URI: "https://alfresco-gateway.REPLACEME/workspace/assets/silent-refresh.html"

alfresco-content-services-community:
  enabled: false
  repository: *alfresco-content-services-repository
  alfresco-infrastructure: *alfresco-content-services-alfresco-infrastructure
