# Default values for chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

global:
  ## Configure pull secrets for all deployments
  registryPullSecrets:
    - "quay-registry-secret"

  keycloak:
    ## Configure Keycloak host template, i.e. "identity.{{ .Release.Namespace }}.{{ .Values.global.gateway.domain }}"
#    host: "identity.{{ .Values.global.gateway.domain }}"

    ## Set full url to configure external Keycloak, https://keycloak.mydomain.com/auth
    url: ""

    ## Configure Keycloak realm
    realm: "alfresco"
    resource: "activiti"
    client: "activiti"

  gateway:
    ## Set to configure single domain name for all services, i.e. "gateway.{{ .Release.Namespace }}.{{ .Values.global.gateway.domain }}"
#    host: "gateway.{{ .Values.global.gateway.domain }}"

    ## Set to false enables HTTPS configuration on all urls
    http: "false"

    ## Set to enable automatic TLS for ingress if https is enabled
    tlsacme: "false"

    ## Set to configure gateway domain template, i.e. {{ .Release.Namespace }}.1.3.4.5.nip.io
    #  helm upgrade activiti . --install --set global.gateway.domain=1.2.3.4.nip.io
    domain: "REPLACEME"

    ## Configure global annotations for all service ingresses, i.e.
    annotations:
      certmanager.k8s.io/issuer: "letsencrypt-prod"
      kubernetes.io/ingress.class: nginx
      nginx.ingress.kubernetes.io/enable-cors: "true"
      nginx.ingress.kubernetes.io/cors-allow-headers: "*"
      nginx.ingress.kubernetes.io/x-forwarded-prefix: "true"

# set to false to disable custom alfresco-identity-service ingress with hostname support
alfresco-identity-service:
  ingress:
    enabled: true

alfresco-infrastructure:
  enabled: true
  alfresco-event-gateway:
    enabled: false
  # patch for https://issues.alfresco.com/jira/browse/DEPLOY-673
  activemq:
    image:
      tag: 5.15.6-java-8-oracle-centos-7-ac5b98b35cd4
  nginx-ingress:
    enabled: false
    controller:
      scope:
        enabled: false
  alfresco-identity-service:
    enabled: true
    ingress:
      enabled: false
    keycloak:
      keycloak:
        service:
          port: 80
        extraArgs: "-Dkeycloak.import=/realm/alfresco-aps-realm.json"
        # Add explicit support for HTTPS proxy address forwarding
        extraEnv: |
          - name: PROXY_ADDRESS_FORWARDING
            value: "true"
    realm:
      alfresco:
        client:
          redirectUris:
            - "*"
          webOrigins:
            - "*"

alfresco-content-services:
  enabled: false
  registryPullSecrets: quay-registry-secret
  externalHost: &alfresco-content-services-external-host '{{ template "common.gateway-host" . }}'
  externalProtocol: &alfresco-content-services-external-protocol '{{ template "common.gateway-proto" . }}'
  messageBroker:
    url:
    user: admin
    password: admin
  alfresco-infrastructure: &alfresco-content-services-alfresco-infrastructure
    enabled: false
    activemq:
      enabled: false
  networkpolicysetting: &alfresco-content-services-networkpolicysetting
    enabled: false
  alfresco-digital-workspace:
    networkpolicysetting:
      enabled: false
  repository: &alfresco-content-services-repository
    replicaCount: 1
    ingress:
      hostName: '{{ template "common.gateway-host" . }}'
      path: "/alfresco"
    environment:
      IDENTITY_SERVICE_URI: '{{ template "alfresco-process-infrastructure.keycloak-url" . }}'
      IDENTITY_SERVICE_REALM: "alfresco"
      IDENTITY_SERVICE_RESOURCE: "activiti"
      JAVA_OPTS: "
        -Dsolr.base.url=/solr
        -Dsolr.secureComms=none
        -Dindex.subsystem.name=solr6
        -Dalfresco.cluster.enabled=true
        -Ddeployment.method=HELM_CHART
        -Xms1800M -Xmx1800M
        -Dauthentication.chain=identity-service1:identity-service,alfrescoNtlm1:alfrescoNtlm
        -Didentity-service.enable-basic-auth=true
        -Didentity-service.authentication.validation.failure.silent=false
        -Didentity-service.auth-server-url=\"$IDENTITY_SERVICE_URI\"
        -Didentity-service.realm=\"$IDENTITY_SERVICE_REALM\"
        -Didentity-service.resource=\"$IDENTITY_SERVICE_RESOURCE\"
        -Dlocal.transform.service.enabled=false
        -Dtransform.service.enabled=false
      "
  share: &alfresco-content-services-share
    replicaCount: 1
    ingress:
      hostName: "{{ .Values.global.gateway.host }}"
  imagemagick:
    replicaCount: 1
  libreoffice:
    replicaCount: 1
  pdfrenderer:
    replicaCount: 1
  tika:
    replicaCount: 1
  transformrouter:
    replicaCount: 1

alfresco-digital-workspace:
  enabled: false # required to disable the one from alfresco-content-services
  image:
    repository: quay.io/alfresco/alfresco-digital-workspace
    tag: 1.1.0
    internalPort: 8080
  ingress:
    path: /workspace
    annotations:
      nginx.ingress.kubernetes.io/proxy-body-size: "5g"
  env:
    APP_CONFIG_AUTH_TYPE: "OAUTH"
    BASEPATH: "./"

alfresco-content-services-community:
  enabled: false
  externalHost: *alfresco-content-services-external-host
  externalProtocol: *alfresco-content-services-external-protocol
  networkpolicysetting: *alfresco-content-services-networkpolicysetting
  repository: *alfresco-content-services-repository
  share: *alfresco-content-services-share
  alfresco-infrastructure: *alfresco-content-services-alfresco-infrastructure
