apiVersion: v1
kind: Secret
metadata:
  name: realm-secret
  labels:
    app: {{ template "alfresco-process-services-infrastructure.name" . }}
    chart: {{ template "alfresco-process-services-infrastructure.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  "springboot-realm.json": {{ .Files.Get "springboot-realm.json" | b64enc }}
