# Default values for chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

alfresco-infrastructure:
  rabbitmq-ha:
    enabled: false
  activemq:
    enabled: false
  alfresco-activiti-cloud-registry:
    enabled: false
  alfresco-api-gateway:
    enabled: false
  nginx-ingress:
    controller:
      scope:
        enabled: false
  alfresco-identity-service:
    keycloak:
      keycloak:
        extraArgs: "-Dkeycloak.import=/realm/springboot-realm.json"
