# Default values for chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

alfresco-infrastructure:
  enabled: true
  rabbitmq-ha:
    enabled: false
  activemq:
    enabled: false
  alfresco-activiti-cloud-registry:
    enabled: false
  alfresco-api-gateway:
    enabled: false
  nginx-ingress:
    controller:
      scope:
        enabled: false
      config:
        ssl-redirect: "false"
        use-proxy-protocol: "false"
  alfresco-identity-service:
    keycloak:
      keycloak:
        image:
#          repository: quay.io/alfresco/keycloak
#          pullSecrets:
#          - name: quay-registry-secret
          tag: 4.5.0.Final
        extraArgs: "-Djava.net.preferIPv4Stack=true -Dkeycloak.import=/realm/springboot-realm.json"
        preStartScript: "cp -p /opt/jboss/tools/docker-entrypoint.sh /opt/jboss/docker-entrypoint.sh"

alfresco-content-services:
  enabled: true
  networkpolicysetting:
    enabled: false
  registryPullSecrets: quay-registry-secret
  alfresco-infrastructure:
    enabled: false
  repository:
    replicaCount: 1
    environment:
      # The IDENTITY_SERVICE_URI should contain the details of the ingress host and port.
      IDENTITY_SERVICE_URI: "<ingresscontrollerurl>/auth"
      IDENTITY_SERVICE_REALM: "springboot"
      IDENTITY_SERVICE_RESOURCE: "activiti"
      JAVA_OPTS: " -Dsolr.base.url=/solr
        -Dsolr.secureComms=none
        -Dindex.subsystem.name=solr6
        -Ddeployment.method=HELM_CHART
        -Xms2000M -Xmx2000M
        -Dauthentication.chain=identity-service1:identity-service,alfrescoNtlm1:alfrescoNtlm
        -Didentity-service.enable-basic-auth=true
        -Didentity-service.authentication.validation.failure.silent=false
        -Didentity-service.auth-server-url=\"$IDENTITY_SERVICE_URI\"
        -Didentity-service.realm=\"$IDENTITY_SERVICE_REALM\"
        -Didentity-service.resource=\"$IDENTITY_SERVICE_RESOURCE\"
        -Dcsrf.filter.enabled=false"
