# Default values for chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

alfresco-infrastructure:
  rabbitmq-ha:
    enabled: false
  activemq:
    enabled: false
  alfresco-activiti-cloud-registry:
    enabled: false
  alfresco-api-gateway:
    enabled: false
  nginx-ingress:
    controller:
      scope:
        enabled: false 
      config:
        ssl-redirect: "false"
        use-proxy-protocol: "false"
  alfresco-identity-service:
    keycloak:
      keycloak:
        extraArgs: "-Dkeycloak.import=/realm/springboot-realm.json"

alfresco-content-services:
  enabled: true
  registryPullSecrets: quay-registry-secret
  alfresco-infrastructure:
    enabled: false
  repository:
    replicaCount: 1
    environment:
      ACTIVEMQ_HOST: "<infrastructure-releasename>-activemq-broker"
      SYNC_SERVICE_URI: "<ingresscontrollerurl>/syncservice"
      # The IDENTITY_SERVICE_URI should contain the details of the ingress host and port.
      IDENTITY_SERVICE_URI: "<ingresscontrollerurl>/auth"
      JAVA_OPTS: " -Dsolr.base.url=/solr
        -Dsolr.secureComms=none
        -Dindex.subsystem.name=solr6
        -Dalfresco.cluster.enabled=true
        -Ddeployment.method=HELM_CHART
        -Xms2000M -Xmx2000M
        -Ddsync.service.uris=\"$SYNC_SERVICE_URI\"
        -Dmessaging.broker.url=\"failover:(tcp://${ACTIVEMQ_HOST}:61616)?timeout=3000\"
        -Dauthentication.chain=identity-service1:identity-service,alfrescoNtlm1:alfrescoNtlm
        -Didentity-service.enable-basic-auth=true
        -Didentity-service.authentication.validation.failure.silent=false
        -Didentity-service.auth-server-url=\"$IDENTITY_SERVICE_URI\"
        -Didentity-service.realm=springboot
        -Didentity-service.resource=activiti"
