apiVersion: v1
kind: Secret
metadata:
  name: {{ index .Values "alfresco-deployment-service" "dockerRegistry" "secretName" }}
  labels:
    app:  "{{ .Release.Name }}-{{ .Chart.Name }}"
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"  
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "alfresco-process-infrastructure.ads-registry-secret" . }}