apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
  labels:
    app: {{ template "alfresco-process-infrastructure.name" . }}
    chart: {{ template "alfresco-process-infrastructure.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
{{- (.Files.Glob "*.sh").AsConfig | nindent 2 }}