{{- if contains "alfresco-aps-realm.json" .Values.alfresco-infrastructure.alfresco-identity-service.keycloak.keycloak.extraArgs }}
apiVersion: v1
kind: Secret
metadata:
  name: realm-secret
  labels:
    app: {{ template "alfresco-process-infrastructure.name" . }}
    chart: {{ template "alfresco-process-infrastructure.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  "alfresco-aps-realm.json": {{ .Files.Get "alfresco-aps-realm.json" | b64enc }}
{{- end}}
