name: Enforce PR Conventions

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - edited
    branches:
      - develop
jobs:
  enforce-pr-conventions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: enforce-pr-conventions
        id: git-naming-convention
        uses: Alfresco/alfresco-build-tools/.github/actions/enforce-pr-conventions@da99ab845e78301fcb0680d16cbc185a40a1938c # v18.24.1
        with:
          jira-project-key: AAE|HXOR
