name: Enforce PR Conventions

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - edited
    branches:
      - develop
jobs:
  enforce-pr-conventions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5.0.1
      - name: enforce-pr-conventions
        id: git-naming-convention
        uses: Alfresco/alfresco-build-tools/.github/actions/enforce-pr-conventions@7bb0d8f13a52db230cff8d3e2895880d6a11c66a # v9.3.3
        with:
          jira-project-key: AAE|HXOR
