{{- if .Values.persistence.enabled }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ .Release.Name }}
spec:
  {{- with .Values.persistence.storageClassName }}
  storageClassName: {{ . }}
  {{- end }}
  {{- with .Values.persistence.accessModes }}
  accessModes:
    {{- range . }}
    - {{ . }}
    {{- end }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.baseSize | default "1Gi" | quote }}
  {{- end }}
