{{- if and .Values.persistence.enabled .Values.volumeinit.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: volume-init
spec:
  template:
    spec:
      restartPolicy: OnFailure
      {{- with .Values.global.registryPullSecrets }}
      imagePullSecrets:
       {{- range $key := . }}
        - name: {{ $key }}
       {{- end }}
      {{- end}}
      volumes:
        - name: {{ .Release.Name }}
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}
      containers:
        - name: volume-init
          image: {{ .Values.volumeinit.image.repository }}:{{ .Values.volumeinit.image.tag }}
          imagePullPolicy: {{ .Values.volumeinit.image.pullPolicy }}
          volumeMounts:
            - name: {{ .Release.Name }}
              mountPath: /home/alfresco/.activiti/project-release-volume/{{ .Values.global.applicationVersion }}
              readOnly: false
{{- end }}
